Traceback (most recent call last):
  File "C:/Darsh Files/Automate the boring stuff with Python/Traceback Module/traceback-module.py", line 3, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
